from __future__ import annotations

from typing import Protocol

from .models import AppSettings, MonitorTask, NormalizedListItem, RunLog, SummaryResult


class SecretStore(Protocol):
    def get(self, service: str, name: str) -> str | None: ...
    def set(self, service: str, name: str, value: str) -> None: ...
    def delete(self, service: str, name: str) -> None: ...


class TaskRepositoryProtocol(Protocol):
    def create(self, task: MonitorTask) -> MonitorTask: ...
    def update(self, task: MonitorTask) -> MonitorTask: ...
    def delete(self, task_id: int) -> None: ...
    def get(self, task_id: int) -> MonitorTask | None: ...
    def list(self) -> list[MonitorTask]: ...
    def due_tasks(self, now: object) -> list[MonitorTask]: ...


class SettingsRepositoryProtocol(Protocol):
    def load(self) -> AppSettings: ...
    def save(self, settings: AppSettings) -> None: ...


class RunLogRepositoryProtocol(Protocol):
    def create_running(self, task_id: int) -> RunLog: ...
    def finish(self, run_id: int, status: str, error: str | None = None) -> None: ...
    def recent(self, limit: int = 200) -> list[RunLog]: ...


class ListExtractorProtocol(Protocol):
    def extract(self, task: MonitorTask, content: bytes, content_type: str, encoding: str) -> list[NormalizedListItem]: ...


class SummarizerProtocol(Protocol):
    async def summarize(self, title: str, text: str, url: str | None) -> SummaryResult: ...


class NotifierProtocol(Protocol):
    async def send_event(self, task: MonitorTask, title: str, url: str | None, summary: SummaryResult) -> None: ...
    async def send_task_failure(self, task: MonitorTask, error: str) -> None: ...
